apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stats
  labels:
    app: stats
    project: gamitude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
        - name: stats
          image: STATS_IMAGE
          env:
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-string
                  key: connection_string
            - name: AppSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: token-string
                  key: token_string
          ports:
            - name: stats-http
              containerPort: 80
          livenessProbe: # Used by deployment controller
            httpGet:
              path: /api/stats/version
              port: 80
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 50
          readinessProbe: # Used by Ingress/GCLB
            httpGet:
              path: /api/stats/version
              port: 80
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 50
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 50m
